flask01/board/models.py
from app import db

# db.Model을 상속받은 테이블을 만듭니다.
class Question(db.Model):   
    id = db.Column(db.Integer, primary_key=True)
    subject = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)

class Answer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    # ondelete='CASCADE' 옵션
    question_id = db.Column(db.Integer, db.ForeignKey('question.id', ondelete='CASCADE'))
    # backref 역참조
    question = db.relationship('Question', backref=db.backref('answer_set'))
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)    

flask01/app.py
# flask run --debug --port 5001
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
# flask db init
# flask db migrate
# flask db upgrade 

import config

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    # 입구 파일을 하나 만들어줍니다.
    app = Flask(__name__)
    app.config.from_object(config)

    # ORM을 적용
    db.init_app(app)
    migrate.init_app(app, db)

    from board.views import main_views, board_views
    app.register_blueprint(main_views.mbp)
    app.register_blueprint(board_views.cbp)

    return app

flask01/board/__init__.py
# __init__ 이라는 파일명을 읽어서 app의 조각이구나 인식함

flask01/board/views/board_views.py
# Blueprint 기능을 사용해서 collection/no2/
from flask import Blueprint, render_template
from ..models import Question

cbp = Blueprint('board', __name__, url_prefix='/board')


# templates 디렉토리 안에 들어있는 file 경로를 읽고, view에 작성한 객체를 달아서 렌더링해서 전달
# 전체 게시글을 db에서 조회해서 가져와서 리스트
@cbp.route('/list')
def list():
    question = Question.query.all()
    return render_template('board/boardList.html', question_list=question)

# 개별 게시글을 조회할 수 있는 함수
@cbp.route('/detail/<int:question_id>/')
def detail(question_id):
    # get_or_404() 메서드로 값을 조회하면 404에러를 발생시킵니다.
    # question = Question.query.get(question_id)
    question = Question.query.get_or_404(question_id)
    return render_template('board/boardDetail.html', question=question)

# 개별 게시글을 작성

# 개별 게시글을 삭제

# 개별 게시글을 수정

# 댓글 작성

# 댓글 수정

# 댓글 삭제


# Blueprint 기능을 사용해서 collection/no1/
@cbp.route('/no1')
def hello2():
    return f'{__name__} 첫번째'
    
@cbp.route('/no2')
def hello3():
    return f'{__name__} 두번째'
    

flask01/board/views/main_views.py
from flask import Blueprint, render_template
from ..models import Question
# 특정 /main/ 하위에 있는 함수들을 일괄적으로 관리하기 위한 flask의 기능
                # 코드에서 부르는 상대적 이름, 실제 파일명, url에 매칭되는 경로 
mbp = Blueprint('main', __name__, url_prefix='/')

# Flask에서 값을 주소줄로 입력받아서 사용하는 방법

# 5001 로 접속하면 index.html 을 화면에 랜더링링
@mbp.route('/')
def index():
    return render_template('index.html')

# <자료형:변수명>
# <path:변수명> : /를 포함한 서브경로 전달

#@mbp.route('/path/<path:subpath>')
#def print_path(subpath):
#    return f'{__name__} {subpath}hello'

#@mbp.route('/items/')
#@mbp.route('/items/<itemname>')
#@mbp.route('/items/<itemname>/<int:quantity>')
#def print_items(itemname='기본값', quantity=0):
#    return f'{__name__} {itemname, quantity} hello'

flask01/views/main_views.py
from flask import Blueprint

# 특정 /main/ 하위에 있는 함수들을 일괄적으로 관리하기 위한 flask의 기능
                # 코드에서 부르는 상대적 이름, 실제 파일명, url에 매칭되는 경로 
mbp = Blueprint('main', __name__, url_prefix='/main')

# Flask에서 값을 주소줄로 입력받아서 사용하는 방법
# <변수명> /변수명
@mbp.route('/<username>')
def print_name(username):
    return f'{__name__} {username}hello'

# <자료형:변수명>
# <path:변수명> : /를 포함한 서브경로 전달

@mbp.route('/path/<path:subpath>')
def print_path(subpath):
    return f'{__name__} {subpath}hello'

@mbp.route('/items/')
@mbp.route('/items/<itemname>')
@mbp.route('/items/<itemname>/<int:quantity>')
def print_items(itemname='기본값', quantity=0):
    return f'{__name__} {itemname, quantity} hello'

flask01/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About 김연지</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <style>
        /* The navigation bar */
            .navbar {
            overflow: hidden;
            background-color: #333;
            position: fixed; /* Set the navbar to fixed position */
            top: 0; /* Position the navbar at the top of the page */
            width: 100%; /* Full width */
            }

            #footer {
            overflow: hidden;
            background-color: #333;
            position: fixed; /* Set the navbar to fixed position */
            left: 0;
            right: 0;
            bottom: 0; /* Position the navbar at the top of the page */
            width: 100%; /* Full width */
            }
    </style>
</head>
<body>

<!-- Header-->
<div id="header" class="py-5">
    {% include 'navbar.html' %}
</div>
{% block content %}





{% endblock %}
<!-- Footer-->
    {% include 'footer.html' %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

</body>
</html>

flask01/templates/board/boardDetail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

flask01/templates/board/boardList.html
{% extends 'base.html' %}
{% block content %}
 
<!-- 질문 목록 -->
{#  render_template 함수에서 전달받은 질문 목록 데이터 question_list가 있는지 검사 #}

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>
                <a href="{{ url_for('board.detail', question_id=question.id) }}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>

{% endblock %}

flask01/templates/footer.html
<div id="footer" class="bg-dark py-4 mt-auto">
    <div class="container px-5">
        <div class="row align-items-center justify-content-between flex-column flex-sm-row">
            <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; YEONJIKIM 2025</div></div>
            <div class="col-auto">
                <span class="text-white mx-1">atangi@naver.com</span>
                <span class="text-white mx-1">&middot;</span>
                <a class="link-light small" href="mailto:atangi@naver.com">Contact</a>
            </div>
        </div>
    </div>
</div>

flask01/templates/index.html
{% extends 'base.html' %}

{% block content %}
<!-- Main-->
<div id="main">

    <div class="container px-5" id="one">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-xxl-6">
                <div class="text-center my-5">
                    <h1 class="fw-bolder mb-3">Build things that build things!</h1>
                    <p class="lead fw-normal text-muted mb-4">김연지입니다</p>
                    <a class="btn btn-dark btn-lg" href="#scroll-target">WHO I AM</a>
                </div>
            </div>
        </div>
    </div>

            <!-- About section one-->
            <section class="py-5 bg-light about_me" id="scroll-target">
                <div class="container px-5 my-5"  id="two">
                    <div class="row gx-5 align-items-center">
                        <div class="col-lg-6"><img class="img-fluid rounded mb-5 mb-lg-0" src="data/spongebob.jpg" alt="..." /></div>
                        <div class="col-lg-6">
                            <h2 class="fw-bolder">Programmer & Educator </h2>
                            <p class="lead fw-normal text-muted mb-0">1000번 안 되다가 1번 될 때 느끼는 희열감과<br>
                                내일은 되겠지, 라는 낙천성을 가진 개발자이자<br>1000번 이해 안 되다가 1번 이해할<br>돈오점수의 순간을 기다리는 개발 강사</p>
                        </div>
                    </div>
                </div>
            </section>
            <!-- About section two-->
            <section class="py-5" id="three">
                <div class="container px-5 my-5">
                    <div class="row gx-5 align-items-center">
                        <div class="col-lg-6 order-first order-lg-last"><img class="img-fluid rounded mb-5 mb-lg-0" src="data/profile.png" alt="..." /></div>
                        <div class="col-lg-6">
                            <h2 class="fw-bolder">Technical Editor</h2>
                            <p class="lead fw-normal text-muted mb-0">국어국문학을 전공한 개발자의 눈으로<br> 잘 이해되는 설명과 잘 돌아가는 코드를 가진<br> 책을 세상에 선보이는 지식노동자</p>
                        </div>
                    </div>
                </div>
            </section>

</div>
{% endblock %}

flask01/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container px-5">
        <a class="navbar-brand">YEONJI KIM</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="#one">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#two">Developer</a></li>
                <li class="nav-item"><a class="nav-link" href="#three">Technical Editor</a></li>
            </ul>

        </div>
    </div>
</nav>